# Generated by Django 5.2.1 on 2025-05-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='agendamento',
            options={'managed': False},
        ),
    ]
