# Generated by Django 4.1.7 on 2025-05-31 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario', models.DateTimeField()),
                ('duracao_consulta', models.IntegerField(blank=True, null=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('bloqueado', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='EspecialidadeMedica',
            new_name='Especialidade',
        ),
        migrations.RemoveField(
            model_name='horariodisponivel',
            name='disponibilidade',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='data',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='duracao_estimada',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='duracao_final',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='especialidade_consulta',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='horario_consulta',
        ),
        migrations.AddField(
            model_name='consulta',
            name='especialidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sistema_agendamento.especialidade'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='tempo_experiencia',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='DisponibilidadeMedico',
        ),
        migrations.DeleteModel(
            name='EspecialidadeConsulta',
        ),
        migrations.DeleteModel(
            name='HorarioDisponivel',
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sistema_agendamento.profissional'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='disponibilidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sistema_agendamento.disponibilidade'),
        ),
    ]
