# Generated by Django 5.2.1 on 2025-05-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0002_paciente_alter_agendamento_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agendamento',
            table='consulta',
        ),
    ]
