# Generated by Django 4.1.7 on 2025-06-01 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0002_disponibilidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='convenio',
        ),
        migrations.AddField(
            model_name='consulta',
            name='plano_saude',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sistema_agendamento.planosaude'),
        ),
    ]
