# Generated by Django 4.1.7 on 2025-06-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0003_remove_consulta_convenio_consulta_plano_saude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='crm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
