# Generated by Django 4.1.7 on 2025-07-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0004_profissional_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Outro', 'N'), ('Selecionar', 'S')], default='Selecionar', max_length=10),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Outro', 'N'), ('Selecionar', 'S')], default='Selecionar', max_length=10),
        ),
    ]
