# Generated by Django 4.1.7 on 2025-07-27 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0004_profissional_crm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.CharField(blank=True, max_length=1, null=True)),
                ('subgrupo', models.CharField(blank=True, max_length=11, null=True)),
                ('subcategoria', models.CharField(blank=True, max_length=11, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='prescricao',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='obs_medicas',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='especialidade_medica',
        ),
        migrations.AddField(
            model_name='profissional',
            name='especialidades_medicas',
            field=models.ManyToManyField(to='app_sistema_agendamento.especialidade'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='situacao',
            field=models.CharField(choices=[('Emergência - Atendimento imediato', 'Emergencia'), ('Muito urgente - Atendimento em até 10 minutos', 'Muito Urgente'), ('Urgente - Atendimento em até 60 minutos', 'Urgente'), ('Pouco urgente - Atendimento em até 2 horas', 'Pouco Urgente'), ('Não urgente - Atendimento em até 4 horas', 'Nao Urgente')], default='Selecionar', max_length=45),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rua',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sistema_agendamento.cid'),
        ),
    ]
