# Generated by Django 4.1.7 on 2025-07-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0005_alter_paciente_sexo_alter_profissional_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Outro', 'Outro'), ('Selecionar', 'Selecionar')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Outro', 'Outro'), ('Selecionar', 'Selecionar')], max_length=10),
        ),
    ]
