# Generated by Django 4.1.7 on 2025-07-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0005_cid_remove_consulta_especialidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='diagnostico',
            new_name='cid',
        ),
        migrations.RemoveField(
            model_name='cid',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='consulta',
            name='subcategoria',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cid',
            name='subgrupo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
