# Generated by Django 4.1.7 on 2025-07-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0007_exames_alter_cid_capitulo_alter_cid_subgrupo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Exames',
        ),
    ]
