# Generated by Django 4.1.7 on 2025-07-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0007_alter_paciente_sexo_alter_profissional_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='obs_medicas',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='especialidade_medica',
        ),
        migrations.AddField(
            model_name='profissional',
            name='especialidades_medicas',
            field=models.ManyToManyField(to='app_sistema_agendamento.especialidade'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='situacao',
            field=models.CharField(choices=[('Emergência - Atendimento imediato', 'Emergencia'), ('Muito urgente - Atendimento em até 10 minutos', 'Muito Urgente'), ('Urgente - Atendimento em até 60 minutos', 'Urgente'), ('Pouco urgente - Atendimento em até 2 horas', 'Pouco Urgente'), ('Não urgente - Atendimento em até 4 horas', 'Nao Urgente')], default='Selecionar', max_length=45),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(default='Selecionar', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rua',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10),
        ),
    ]
