# Generated by Django 4.1.7 on 2025-07-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0008_exame_delete_exames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='exames_solicitados',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sistema_agendamento.exame'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='subcategoria',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], null=True),
        ),
    ]
