# Generated by Django 5.2.1 on 2025-07-27 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0009_alter_consulta_exames_solicitados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cid',
            name='especialidades',
            field=models.ManyToManyField(blank=True, to='app_sistema_agendamento.especialidade'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='disponibilidade',
            field=models.ForeignKey(blank=True, limit_choices_to={'bloqueado': False, 'disponivel': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sistema_agendamento.disponibilidade'),
        ),
    ]
