# Generated by Django 4.1.7 on 2025-07-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0009_alter_consulta_exames_solicitados_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consulta',
            new_name='Agendamento',
        ),
    ]
