# Generated by Django 5.2.1 on 2025-07-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0010_cid_especialidades_alter_consulta_disponibilidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cid',
            name='especialidades',
        ),
        migrations.AddField(
            model_name='planosaude',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='planosaude',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='planosaude',
            name='razao_social',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Razão Social'),
        ),
        migrations.AddField(
            model_name='planosaude',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone de contato'),
        ),
        migrations.AlterField(
            model_name='planosaude',
            name='nome',
            field=models.CharField(default='Plano Desconhecido', max_length=100, verbose_name='Nome do plano'),
        ),
    ]
