# Generated by Django 4.1.7 on 2025-07-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0010_rename_consulta_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='tempo_experiencia',
        ),
    ]
