# Generated by Django 5.2.1 on 2025-07-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0011_remove_cid_especialidades_planosaude_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteplano',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pacienteplano',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
