# Generated by Django 4.1.7 on 2025-08-02 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0011_remove_profissional_tempo_experiencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sistema_agendamento.agendamento')),
            ],
        ),
    ]
