# Generated by Django 4.1.7 on 2025-08-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0013_rename_consulta_consultacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consultacao',
            new_name='Consulta',
        ),
    ]
