# Generated by Django 4.1.7 on 2025-08-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0014_rename_consultacao_consulta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='descricao',
            new_name='observacoes',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='exames_solicitados',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='consulta',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sistema_agendamento.cid'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='exames_solicitados',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sistema_agendamento.exame'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='subcategoria',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], null=True),
        ),
    ]
