# Generated by Django 4.1.7 on 2025-08-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0015_rename_descricao_agendamento_observacoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='situacao',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='exames_solicitados',
        ),
        migrations.AddField(
            model_name='consulta',
            name='exames_solicitados',
            field=models.ManyToManyField(to='app_sistema_agendamento.exame'),
        ),
    ]
