# Generated by Django 4.1.7 on 2025-08-02 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_agendamento', '0016_remove_agendamento_situacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('sigla', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='rua',
        ),
        migrations.AddField(
            model_name='paciente',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sistema_agendamento.cidade'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sistema_agendamento.estado'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='logradouro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sistema_agendamento.logradouro'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sistema_agendamento.cidade'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sistema_agendamento.estado'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='logradouro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sistema_agendamento.logradouro'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sistema_agendamento.bairro'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sistema_agendamento.bairro'),
        ),
    ]
